#!/bin/bash

#
#  Copyright 2008-2012 Alex Vesev
#
#  This file is part of DMLEncr Storage. DMLEncr should be unwraped as
#  DM & LUKS Encrypted Storage Manager.
#
#  DMLEncr Storage is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  DMLEncr Storage is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with DMLEncr Storage.  If not, see <http://www.gnu.org/licenses/>.
#
##

declare -ri noError=0 # Zero is OK
declare -ri errorMisc=1
declare -ri undefinedErrorState=253
declare -ri errorEpic=254
declare -ri stateIsMounted=100
declare -ri stateIsNotMounted=101
declare     stateOfProcess=${noError}

declare -ri codeSuccess=0
declare -ri codeFailure=1

function printSudoersPolicyExample {
cat <<- EOF
#
# You may set up DMLEncr sudoers policy,
# if you need it:
#
# allowedUser ALL = NOPASSWD: "${dirInstall}/$( basename "${fileDMLEncr}" )" m
# allowedUser ALL = NOPASSWD: "${dirInstall}/$( basename "${fileDMLEncr}" )" u
#
EOF
}

[ ${UID} != 0 ] \
    && echo "ERROR:${0}:${LINENO}: This script must be run as root." >&2 \
    && stateOfProcess=${errorMisc} \
    && exit ${stateOfProcess}

declare -r dirInstall="/usr/bin"
declare -r dirSource="."
declare -r fileDMLEncr="dmlencr"

function installDMLEncr {
    for targetFileObjectName in "${dirInstall}" "${dirSource}/${fileDMLEncr}" ; do
        [ ! -e "${targetFileObjectName}" ] \
            && echo "ERROR:${0}:${LINENO}: Not found object '${targetFileObjectName}'." >&2 \
            && stateOfProcess=${errorMisc}
    done

    install -D --owner=root --group=root --mode 755 "${dirSource}/${fileDMLEncr}" "${dirInstall}"
    [ ${?} != 0 ] \
        && stateOfProcess=${errorMisc}

    printSudoersPolicyExample

    [ ${stateOfProcess} != ${noError} ] \
        && echo "ERROR:${0}:${LINENO}: Finished with errors." >&2
    exit ${stateOfProcess}
}

function uninstallDMLEncr {
    rm -f "${dirInstall}/${fileDMLEncr}"
}

function showDoc {
echo "
USAGE IS

    $( basename "${0}" ) options

OPTIONS

    --install

    --uninstall

    --help

COPYRIGHT AND LICENCE

Copyright © 2012 Alex Vesev. License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.

This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.



"
}





[ ${#} == 0 ] \
    && showDoc \
    && exit ${errorMisc}
while [ ${#} != 0 ] ; do
    argument="${1#--}" # Strip leading '--'.
    argument="${argument%%=*}" # Strip trailing '=*'
    case "${argument}" in
    help)
        showDoc
        exit ${stateOfProcess}
    ;;
    install)
        installDMLEncr
    ;;
    uninstall)
        uninstallDMLEncr
    ;;
    *)
        echo "Error [ ${0} ]:${LINENO}: Unknown parameter name '${1%%=*}'. Try '--help'." >&2
        exit ${errorMisc}
    ;;
    esac
    shift 1
done
